unbind C-b
set -g prefix `

# As suggested in nvim's :checkhealth
set-option -sg escape-time 10
set-option -g default-terminal "tmux-256color"

source ~/.config/tmux/numbering.tmux
source ~/.config/tmux/pane_movements.tmux
source ~/.config/tmux/colors.tmux
source ~/.config/tmux/history.tmux
source ~/.config/tmux/bind.tmux

# To move between sessions faster
set-option -g detach-on-destroy off
bind X run-shell "tmux-close-session"
bind x kill-pane
bind h switch-client -l
bind -n M-a switch-client -l

set -g @session-wizard 's'
run-shell ~/sources/tmux/tmux-session-wizard/session-wizard.tmux

bind C-n display-popup \
  -w 80% \
  -h 80% \
  -E 'nvim ./notes'
