unbind C-b
set -g prefix `

# As suggested in nvim's :checkhealth
set-option -sg escape-time 10
set-option -g default-terminal "tmux-256color"

# Focus events enabled for terminals that support them
set -g focus-events on

source ~/.config/tmux/numbering.tmux
source ~/.config/tmux/pane_movements.tmux
source ~/.config/tmux/colors.tmux
source ~/.config/tmux/history.tmux
source ~/.config/tmux/bind.tmux
source ~/.config/tmux/sessions.tmux
source ~/.config/tmux/statusline.tmux
